"""gen_tables.py — write the lookup tables the HDMI demo uses as Verilog ROMs.

    python fpga_fft/gen_tables.py        # -> src/hdmi/rom_sine.v, src/hdmi/rom_hann.v

Each table is a 1024-entry ROM with a registered output (one clock from address to data),
written as a case statement so Gowin synthesis can place it in a block RAM.
  rom_sine  round(32767 * sin(2*pi*k/1024)), signed: one full sine period (test tone)
  rom_hann  round(32767 * 0.5 * (1 - cos(2*pi*k/1024))), 0..32767: the Hann window
"""
from pathlib import Path
import math

OUT = Path(__file__).resolve().parent / "src" / "hdmi"


def rom(name: str, comment: str, values: list[int], signed: bool) -> None:
    lines = [f"// {name}.v — generated by fpga_fft/gen_tables.py, do not edit.",
             f"// {comment}",
             f"module {name} (",
             "    input  wire        clk,",
             "    input  wire [9:0]  addr,",
             f"    output reg  {'signed ' if signed else ''}[15:0] q = 0",
             ");",
             "    always @(posedge clk)",
             "        case (addr)"]
    for k, v in enumerate(values):
        lines.append(f"            10'd{k}: q <= {'-' if v < 0 else ''}16'sd{abs(v)};" if signed
                     else f"            10'd{k}: q <= 16'd{v};")
    lines += ["        endcase", "endmodule", ""]
    (OUT / f"{name}.v").write_text("\n".join(lines))
    print(f"wrote {OUT / name}.v")


rom("rom_sine", "One sine period, 1024 steps, amplitude 32767 (the test tone).",
    [round(32767 * math.sin(2 * math.pi * k / 1024)) for k in range(1024)], True)
rom("rom_hann", "Hann window, 1024 points, 0..32767 (Q15): fades each block in and out.",
    [round(32767 * 0.5 * (1 - math.cos(2 * math.pi * k / 1024))) for k in range(1024)], False)
